package sk.m3ii0.smootheditor.code.editor.enums;

public enum MenuAction {
	
	NONE(),
	
	UPDATE_HEAD(),
	UPDATE_BODY(),
	UPDATE_RIGHT_ARM(),
	UPDATE_LEFT_ARM(),
	UPDATE_RIGHT_LEG(),
	UPDATE_LEFT_LEG(),
	
	CHANGE_ARMS_VISIBILITY(),
	CHANGE_BASEPLATE_VISIBILITY(),
	CHANGE_GRAVITY(),
	CHANGE_SIZE(),
	CHANGE_VISIBILITY(),
	CHANGE_CUSTOM_NAME_VISIBILITY(),
	
	VALUE_TO_PLUS(),
	VALUE_TO_MINUS(),
	
	DIRECTION_TO_X(),
	DIRECTION_TO_Y(),
	DIRECTION_TO_Z(),
	
	CHANGE_TO_0_1(),
	CHANGE_TO_0_5(),
	CHANGE_TO_1(),
	CHANGE_TO_10();
	
}
